[project]
name = "sql_to_arc"
dynamic = ["version"]
description = "The FAIRagro advanced middleware SQL-to-ARC converter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "arctrl>=3.0.0b15",
  "pydantic>=2.12.5",
  "fairagro-middleware-api-client>=10.0.1",
  "fairagro-middleware-shared>=10.0.1",
  "opentelemetry-api>=1.30.0",
  "aiomysql>=0.2.0",
  "aioodbc>=0.4.1",
  "oracledb>=2.0.0",
  "psycopg[binary]>=3.3.3",
  "sqlalchemy[asyncio]>=2.0.46",
]

[tool.hatch.version]
source = "vcs"
raw-options = { root = "../.." }

[tool.hatch.build.targets.wheel]
packages = ["src/middleware"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
